CREATE TABLE IF NOT EXISTS users(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(500),
    DATE_OF_BIRTH DATE,
    PASSWORD VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS accounts(
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES users,
    BALANCE DECIMAL NOT NULL DEFAULT 0 CHECK (BALANCE > 0)
);

CREATE TABLE IF NOT EXISTS email_data(
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES users,
    EMAIL VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS phone_data(
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT REFERENCES users,
    PHONE VARCHAR(13)
);

CREATE UNIQUE INDEX emails_unique_indexes ON email_data(EMAIL);
CREATE UNIQUE INDEX phone_unique_indexes ON phone_data(PHONE);