-- Users
INSERT INTO users(NAME, DATE_OF_BIRTH, PASSWORD) VALUES('Alex', CURRENT_DATE, md5('12345'));
INSERT INTO users(NAME, DATE_OF_BIRTH, PASSWORD) VALUES('George', CURRENT_DATE, md5('abcd12'));
INSERT INTO users(NAME, DATE_OF_BIRTH, PASSWORD) VALUES('Eugene', CURRENT_DATE, md5('bcd234'));

-- Accounts
INSERT INTO accounts(USER_ID, BALANCE) VALUES(1, 100);
INSERT INTO accounts(USER_ID, BALANCE) VALUES(2, 500);
INSERT INTO accounts(USER_ID, BALANCE) VALUES(3, 250);

-- Emails
INSERT INTO email_data(USER_ID, EMAIL) VALUES(1, 'first@example.com');
INSERT INTO email_data(USER_ID, EMAIL) VALUES(2, 'second@example.com');
INSERT INTO email_data(USER_ID, EMAIL) VALUES(3, 'third@example.com');

-- Phones
INSERT INTO phone_data(USER_ID, PHONE) VALUES(1, '89540923412');
INSERT INTO phone_data(USER_ID, PHONE) VALUES(2, '89841832838');
INSERT INTO phone_data(USER_ID, PHONE) VALUES(3, '88123290231');